### ISSUE TITLE
unhandled rejection: Rejection(PayloadTooLarge)

### ISSUE THREAD

**Issue by polyphia** [EnsoFinance/temper#10]
First of all I need to say I have no idea if this simulator is a viable option for handling a high amount of txs in a short period of time (in a single request), let's say anything between 200 and 500 txs for a given block . 

Having said that, there is a payload size limit for the server accepting the curl requests and the bottleneck is reached quite easily so simulating anything like even 50 transactions in a single request is impossible . 

I tried modifying warp to accomodate for bigger payload but kept getting the same error . 

`unhandled rejection: Rejection(PayloadTooLarge)`

Where could we modify the maximum payload size please ? 

Thanks

**Comment by ape-dev-cs** [comment]
Could we get a full backtrace? I have a feeling that this may be something to do with the HTTP server.

**Comment by polyphia** [comment]
Yea it's most likely the http server, I thought warp was what was being used so tried to change a few things there . 

This is all I get in the API logs : 

` Compiling transaction-simulator v0.1.0 (/home/sim/transaction-simulator)
    Finished dev [unoptimized + debuginfo] target(s) in 9.41s
     Running `target/debug/transaction-simulator`
 INFO  ts::api > Starting server on port 9080
unhandled rejection: Rejection(PayloadTooLarge)
 INFO  ts::api > 127.0.0.1:38486 "POST /api/v1/simulate-bundle HTTP/1.1" 500 "-" "axios/0.27.2" 347.997µs`

**Comment by devanoneth** [comment]
Hey, it's set here: https://github.com/EnsoFinance/transaction-simulator/blob/main/src/lib.rs#L102

Would be open to a PR which makes it configurable with an env var :)

**Comment by polyphia** [comment]
@devanoneth thanks for this, I can see it now in the last line !

Sadly I don't code in RUST , hopefully someone will do it

**Comment by MartinquaXD** [comment]
Fixed in https://github.com/EnsoFinance/temper/pull/24
